# Init

In [ ]:
# init
from importlib import reload
from pprint import pprint
import os
import sys
from pathlib import Path
import pandas as pd

def reloadPckg():
    reload(tgm)
    reload(too)
    reload(osmt)
    reload(tph)

sys.path.append('..')
sys.path.append('../tools')
devPath = "C:/Users/gonta/D/software developer/"
sys.path.append(os.path.join(devPath, "packages"))


import tests.osm_test as osmt
import toolsGeneral.main as tgm
import toolsGeneral.logger as tgl
import toolsOSM.overpass as too
import toolsPandas.helpers as tph

# Cleaning

## * import

In [1]:
data_dir = Path(os.path.join(os.getcwd(), '..', 'data', 'raw', 'osm countries queries'))
files_dirs = [f for f in data_dir.glob('*')]
print(len(files_dirs))

raw_by_cntr = {}

# for chunks and non chunk files
for dir in files_dirs:
    files_elements = [tgm.load(str(f))['elements'] for f in dir.glob('*.json')]
    elements = [ele for list in files_elements for ele in list]
    raw_by_cntr[str(dir.name)] = elements

print(len(raw_by_cntr))

83
83

In [4]:
path = Path(os.path.join(os.getcwd(),'../data/normalized'))
processsed_countries = [f.name for f in path.glob('*')]
print(len(processsed_countries))
# to_process_raw_by_cntr = {k:v for k,v in raw_by_cntr.items() if k not in processsed_countries}

70

In [13]:
to_process_raw_by_cntr = raw_by_cntr
print(len(to_process_raw_by_cntr))

83

In [8]:
resume = {}
for country, raw in raw_by_cntr.items():
    resume[country] = {}
    resume[country]['lvl_1'] = len([ele for ele in raw if ele['tags']['admin_level'] == '4'])
    resume[country]['lvl_2'] = len([ele for ele in raw if ele['tags']['admin_level'] == '6'])
    resume[country]['lvl_3'] = len([ele for ele in raw if ele['tags']['admin_level'] == '8'])
    resume[country]['total'] = len([ele for ele in raw if ele['tags']['admin_level'] != '2'])

resume = pd.DataFrame(resume)
table = resume.T
tph.df_peek(table)

## * use sovereign countries only

In [9]:
sovereign_countries = tgm.load(os.path.join('..', 'data', 'sovereign countries.json'))
len(sovereign_countries)

214

In [10]:
print(len(raw_by_cntr))
raw_by_cntr = {k:df for k,df in raw_by_cntr.items() if k in sovereign_countries}
len(raw_by_cntr)

83

70

## * clean countries

In [11]:
import copy
def clean_country_data(raw_by_cntr):

    cleaned_by_cntr = copy.deepcopy(raw_by_cntr)  

    for country, raw_data in cleaned_by_cntr.items():

        # convert id to string
        for ele in raw_data:
            ele['id'] = str(ele['id'])

        # add parent_id to level 4 entities
        cntr_id = list(filter(lambda ele: ele['tags']['admin_level'] == '2', raw_data))[0]['id']
        for ele in raw_data:
            if ele['tags']['admin_level'] == '4':
                ele['tags']['parent_id'] = str(cntr_id)

        # add country_name and country_id tag
        for ele in raw_data:
            ele['tags']['country_name'] = country
            ele['tags']['country_id'] = cntr_id

    return cleaned_by_cntr

In [12]:
cleaned_by_cntr = clean_country_data(raw_by_cntr)
print(len(cleaned_by_cntr))

70

In [13]:
temp = [ele['tags'].get('parent_id',None) for k,v in cleaned_by_cntr.items() for ele in v]
pd.Series(temp).map(type).value_counts()

<class 'str'>         120018
<class 'NoneType'>        70
Name: count, dtype: int64

## * convert to dataframe

In [14]:
df_by_cntr = {k:too.normalizeOSM(elems) for k,elems in cleaned_by_cntr.items()}
len(df_by_cntr)

70

In [15]:
combined = pd.concat(df_by_cntr.values(), ignore_index=True)
combined.map(type).stack().value_counts()

<class 'pandas._libs.missing.NAType'>    1058618
<class 'str'>                             862790
Name: count, dtype: int64

## * save

In [16]:
print(len(df_by_cntr))

70

In [19]:
# save data by country
for k,df in df_by_cntr.items():
    path = os.path.join('../data/normalized', k, f'{k}_normalized.pkl')
    tgm.dump(path, df)

## * review

In [20]:
# import
dataDir = Path(os.path.join(os.getcwd(), '..', 'data/normalized'))
rawFiles = [f for f in dataDir.rglob('*.pkl')]
print(len(rawFiles))

df_by_cntr = {
    file.parent.name:tgm.load(str(file))
    for file in rawFiles
}
print(len(df_by_cntr))

70
70

In [21]:
for k,df in df_by_cntr.items():
    cntr = df[df['tags.admin_level']=='2']
    print([k, cntr['tags.name'].iloc[0], cntr['tags.name:en'].iloc[0]])

['Afghanistan', 'افغانستان', 'Afghanistan']
['Albania', 'Shqipëria', 'Albania']
['Algeria', 'Algérie ⵍⵣⵣⴰⵢⴻⵔ الجزائر', 'Algeria']
['Andorra', 'Andorra', 'Andorra']
['Angola', 'Angola', 'Angola']
['Anguilla', 'Anguilla', 'Anguilla']
['AntiguaAndBarbuda', 'Antigua and Barbuda', 'Antigua and Barbuda']
['Argentina', 'Argentina', 'Argentina']
['Armenia', 'Հայաստան', 'Armenia']
['Australia', 'Australia', 'Australia']
['Austria', 'Österreich', 'Austria']
['Bangladesh', 'বাংলাদেশ', 'Bangladesh']
['Belarus', 'Беларусь', 'Belarus']
['Belgium', 'België / Belgique / Belgien', 'Belgium']
['Bhutan', 'འབྲུག་ཡུལ།', 'Bhutan']
['Brazil', 'Brasil', 'Brazil']
['Bulgaria', 'България', 'Bulgaria']
['Cambodia', 'ព្រះរាជាណាចក្រ\u200bកម្ពុជា', 'Cambodia']
['Chile', 'Chile', 'Chile']
['Colombia', 'Colombia', 'Colombia']
['Czechia', 'Česko', 'Czechia']
['Denmark', 'Danmark', 'Denmark']
['Ecuador', 'Ecuador', 'Ecuador']
['Estonia', 'Eesti', 'Estonia']
['Eswatini', 'Eswatini', 'Eswatini']
['FaroeIslands', 'Føroyar', 'Faroe Islands']
['Finland', 'Suomi / Finland', 'Finland']
['Georgia', 'საქართველო', 'Georgia']
['Germany', 'Deutschland', 'Germany']
['Greece', 'Ελλάς', 'Greece']
['Guinea', 'Guinée', 'Guinea']
['Guinea-bissau', 'Guiné-Bissau', 'Guinea-Bissau']
['Hungary', 'Magyarország', 'Hungary']
['Ireland', 'Éire / Ireland', 'Ireland']
['IsleOfMan', 'Isle of Man', 'Isle of Man']
['Jordan', 'الأردن', 'Jordan']
['Kyrgyzstan', 'Кыргызстан', 'Kyrgyzstan']
['Laos', 'ປະເທດລາວ', 'Laos']
['Latvia', 'Latvija', 'Latvia']
['Lebanon', 'لبنان', 'Lebanon']
['Libya', 'ليبيا', 'Libya']
['Lithuania', 'Lietuva', 'Lithuania']
['Mauritania', 'Mauritanie موريتانيا', 'Mauritania']
['Mexico', 'México', 'Mexico']
['Moldova', 'Moldova', 'Moldova']
['Mongolia', 'Монгол улс ᠮᠤᠩᠭᠤᠯ ᠤᠯᠤᠰ', 'Mongolia']
['Montenegro', 'Crna Gora / Црна Гора', 'Montenegro']
['Myanmar', 'မြန်မာ', 'Myanmar']
['Nepal', 'नेपाल', 'Nepal']
['NorthKorea', '조선민주주의인민공화국', 'North Korea']
['NorthMacedonia', 'Северна Македонија', 'North Macedonia']
['Poland', 'Polska', 'Poland']
['Romania', 'România', 'Romania']
['Russia', 'Россия', 'Russia']
['Rwanda', 'Rwanda', 'Rwanda']
['SanMarino', 'San Marino', 'San Marino']
['Senegal', 'Sénégal', 'Senegal']
['SierraLeone', 'Sierra Leone', 'Sierra Leone']
['Slovakia', 'Slovensko', 'Slovakia']
['SouthAfrica', 'South Africa', 'South Africa']
['Sweden', 'Sverige', 'Sweden']
['Switzerland', 'Schweiz/Suisse/Svizzera/Svizra', 'Switzerland']
['Syria', 'سوريا', 'Syria']
['TheGambia', 'Gambia', 'The Gambia']
['Tunisia', 'تونس', 'Tunisia']
['Turkey', 'Türkiye', 'Turkey']
['Ukraine', 'Україна', 'Ukraine']
['UnitedKingdom', 'United Kingdom', 'United Kingdom']
['VaticanCity', 'Civitas Vaticana - Città del Vaticano', 'Vatican City']
['Vietnam', 'Việt Nam', 'Vietnam']

In [22]:
resume = {}
for country, df in df_by_cntr.items():
    resume[country] = {}
    resume[country]['lvl1'] = len(df[df['tags.admin_level'] == '4'])
    resume[country]['lvl2'] = len(df[df['tags.admin_level'] == '6'])
    resume[country]['lvl3'] = len(df[df['tags.admin_level'] == '8'])
    resume[country]['total'] = len(df[df['tags.admin_level'] != '2'])

resume = pd.DataFrame(resume)
table = resume.T
tph.df_peek(table)

## 3. osm duplicates test

### * check data

In [122]:
dups_id = df_all[df_all.duplicated(subset=['id'])]['id'].to_list()
print(len(dups_id))

dups_df = df_all[df_all.duplicated(subset=['id'], keep=False)]
print(len(dups_df))

dups_id_tuples = dups_df[['id','tags.parent_id','tags.country_id']].apply(tuple, axis=1).to_list()
print(len(dups_id_tuples))

1104
1636
1636

In [41]:
dups_id_parent = df_all[df_all.duplicated(subset=['id','tags.parent_id'], keep=False)][['id','tags.parent_id']].apply(tuple, axis=1).to_list()
print(len(dups_id_parent))
dups_id_parent_cntr = df_all[df_all.duplicated(subset=['id','tags.parent_id','tags.country_id'], keep=False)][['id','tags.parent_id','tags.country_id']].apply(tuple, axis=1).to_list()
print(len(dups_id_parent_cntr))

1380
0

In [55]:
df_all[(df_all[['id','tags.parent_id','tags.country_id']] == ('72639', '60199', '60199')).all(axis=1)]

,type,id,tags.admin_level,tags.parent_id,tags.name,tags.name:us,tags.ISO3166-1,tags.ISO3166-2,tags.is_in:country,tags.ref:nuts,tags.ref:nuts:2,tags.ref:nuts:3,tags.addr:country,tags.country_name,tags.country_id
113807,relation,72639,4,60199,Автономна Республіка Крим,<NA>,<NA>,UA-43,<NA>,<NA>,<NA>,<NA>,<NA>,Ukraine,60199

In [ ]:
all_id_tuples = df_all[['id','tags.parent_id','tags.country_id']].fillna('#').apply(tuple, axis=1).to_list()
print(len(all_id_tuples))

In [102]:
to_review_ids = [('72639','60189','60189'), ('72639','60199','60199'),('6543282', '6543265', '192756'),
 ('6543282', '6543273', '192756'), ('59190', '59195', '59065'), ('59190', '59752', '59065')]

In [103]:
tgm.dump(os.path.join(os.getcwd(), "../data/tests results/osm duplicates test", "to_review_ids.pkl"),to_review_ids)

In [51]:
temp1 = too.is_child_inside_parent('6543282','6543265')
[[k,v['result']] for k,v in temp1.items()]

[INFO] :    > Getting admin_centre:
[INFO] :     * Found node (admin_centre)
[INFO] :    > Testing admin_centre node (id: 7934379969)
[INFO] :     * Finished testing (admin_centre): False
[INFO] :    > Getting label:
[INFO] :     * Missing node (label)
[INFO] :    > Getting place:
[INFO] :     * Found node (place)
[INFO] :    > Testing place node (id: 7934379969)
[INFO] :     * Finished testing (place): False
[INFO] :    > Getting geom_node:
[INFO] :     * Found node (geom_node)
[INFO] :    > Testing geom_node node (id: 4298631214)
[INFO] :     * Finished testing (geom_node): True
[INFO] :    > Getting centroid:
[INFO] :     * Found node (centroid)
[INFO] :    > Testing centroid (lat: 36.8944071, lon: 6.4872707)
[INFO] :     * Finished testing (centroid): True

[['admin_centre', False],
 ['label', None],
 ['place', False],
 ['geom_node', True],
 ['centroid', True]]

In [37]:
tph.get_from_df(df_all,['id','tags.parent_id','tags.country_id'],('6543282', '6543265', '192756'))

,type,id,tags.admin_level,tags.parent_id,tags.name,tags.name:us,tags.ISO3166-1,tags.ISO3166-2,tags.is_in:country,tags.ref:nuts,tags.ref:nuts:2,tags.ref:nuts:3,tags.addr:country,tags.country_name,tags.country_id
2462,rel,6543282,8,6543265,Beni Zid ⴱⴻⵏⵉ ⵣⵉⴷ بنى زيد,<NA>,<NA>,<NA>,Algeria,<NA>,<NA>,<NA>,<NA>,Algeria,192756

In [32]:
dups_id_tuples

[('6543282', '6543265', '192756'),
 ('6543282', '6543273', '192756'),
 ('14326718', '3824588', '184640'),
 ('14326687', '3825003', '184640'),
 ('14326687', '3921322', '184640'),
 ('14326718', '3921322', '184640'),
 ('59190', '59752', '59065'),
 ('59190', '59195', '59065'),
 ('5598639', '70809', '59065'),
 ('8030910', '70809', '59065'),
 ('5598639', '70802', '59065'),
 ('8030910', '70802', '59065'),
 ('8075978', '70671', '59065'),
 ('8144265', '69554', '59065'),
 ('8144265', '79911', '59065'),
 ('8075978', '6825778', '59065'),
 ('7400', '4217435', '52411'),
 ('416271', '4217435', '52411'),
 ('7400', '53134', '52411'),
 ('416271', '53134', '52411'),
 ('117571', '7400', '52411'),
 ('1561101', '7400', '52411'),
 ('117571', '416271', '52411'),
 ('1561101', '416271', '52411'),
 ('13482954', '12171908', '184629'),
 ('13482954', '12171907', '184629'),
 ('406273', '405935', '59470'),
 ('406273', '325866', '59470'),
 ('2662003', '362413', '59470'),
 ('2662004', '302819', '59470'),
 ('2662005', '315173', '59470'),
 ('2662005', '334443', '59470'),
 ('2662003', '303702', '59470'),
 ('2662004', '332924', '59470'),
 ('4283101', '3759431', '186382'),
 ('4283101', '3759439', '186382'),
 ('17755316', '3759439', '186382'),
 ('17755317', '3759439', '186382'),
 ('17755318', '3759439', '186382'),
 ('17759455', '3759439', '186382'),
 ('4283101', '3759447', '186382'),
 ('4283101', '3759438', '186382'),
 ('4283101', '3759448', '186382'),
 ('4283101', '3759427', '186382'),
 ('17755316', '3759427', '186382'),
 ('17755317', '3759427', '186382'),
 ('17755318', '3759427', '186382'),
 ('17759455', '3759427', '186382'),
 ('4283101', '3759443', '186382'),
 ('1980749', '153549', '167454'),
 ('1980749', '301542', '167454'),
 ('7128806', '1310024', '120027'),
 ('7128807', '1310024', '120027'),
 ('11908912', '1342095', '120027'),
 ('11908912', '1342117', '120027'),
 ('11919498', '4060568', '120027'),
 ('7128806', '1342133', '120027'),
 ('7128807', '1342133', '120027'),
 ('11919498', '1342124', '120027'),
 ('18963551', '1343269', '120027'),
 ('18963551', '1343276', '120027'),
 ('11909897', '10298142', '120027'),
 ('11909898', '10298142', '120027'),
 ('11909897', '1438574', '120027'),
 ('11909898', '1438574', '120027'),
 ('13466581', '1314678', '120027'),
 ('13466581', '1335179', '120027'),
 ('62442', '62771', '51477'),
 ('62673', '62771', '51477'),
 ('3659532', '62341', '51477'),
 ('3659532', '62372', '51477'),
 ('62442', '62761', '51477'),
 ('62673', '62761', '51477'),
 ('1115033', '62401', '51477'),
 ('1115034', '62401', '51477'),
 ('1115033', '62586', '51477'),
 ('1115034', '62586', '51477'),
 ('155567', '62442', '51477'),
 ('1818486', '62442', '51477'),
 ('155567', '62673', '51477'),
 ('1808583', '62673', '51477'),
 ('1818486', '62673', '51477'),
 ('1808583', '62597', '51477'),
 ('223136', '192307', '192307'),
 ('4496067', '192307', '192307'),
 ('1845173', '4496067', '192307'),
 ('1846634', '4496067', '192307'),
 ('5305784', '4496067', '192307'),
 ('5305896', '4496067', '192307'),
 ('5323564', '4496067', '192307'),
 ('5323577', '4496067', '192307'),
 ('5323612', '4496067', '192307'),
 ('5323628', '4496067', '192307'),
 ('5323643', '4496067', '192307'),
 ('5323832', '4496067', '192307'),
 ('5324073', '4496067', '192307'),
 ('5324074', '4496067', '192307'),
 ('5324075', '4496067', '192307'),
 ('5324202', '4496067', '192307'),
 ('5324235', '4496067', '192307'),
 ('5324258', '4496067', '192307'),
 ('5324274', '4496067', '192307'),
 ('11274601', '4496067', '192307'),
 ('1613889', '223136', '192307'),
 ('1624125', '223136', '192307'),
 ('1645432', '223136', '192307'),
 ('1827275', '223136', '192307'),
 ('1827276', '223136', '192307'),
 ('1827293', '223136', '192307'),
 ('1827294', '223136', '192307'),
 ('1827295', '223136', '192307'),
 ('1827377', '223136', '192307'),
 ('1827378', '223136', '192307'),
 ('1827399', '223136', '192307'),
 ('1827656', '223136', '192307'),
 ('3671798', '223136', '192307'),
 ('5324202', '223136', '192307'),
 ('19258534', '223136', '192307'),
 ('8324061', '5323612', '192307'),
 ('8325070', '5323612', '192307'),
 ('16807920', '5324274', '192307'),
 ('16807921', '5324274', '192307'),
 ('11991949', '956612', '192307'),
 ('11991949', '956611', '192307'),
 ('13241240', '11274601', '192307'),
 ('13241289', '11274601', '192307'),
 ('8443247', '5323628', '192307'),
 ('11814881', '1845173', '192307'),
 ('11814882', '1845173', '192307'),
 ('11814885', '1845173', '192307'),
 ('11814886', '1845173', '192307'),
 ('13256923', '5305784', '192307'),
 ('14865319', '1827656', '192307'),
 ('14865320', '1827656', '192307'),
 ('14865321', '1827656', '192307'),
 ('14865322', '1827656', '192307'),
 ('14865323', '1827656', '192307'),
 ('14865324', '1827656', '192307'),
 ('14865325', '1827656', '192307'),
 ('14865326', '1827656', '192307'),
 ('14865327', '1827656', '192307'),
 ('14865328', '1827656', '192307'),
 ('14865329', '1827656', '192307'),
 ('14865330', '1827656', '192307'),
 ('14865331', '1827656', '192307'),
 ('14865332', '1827656', '192307'),
 ('14865333', '1827656', '192307'),
 ('14865452', '1827656', '192307'),
 ('14865453', '1827656', '192307'),
 ('14865454', '1827656', '192307'),
 ('14865486', '1827656', '192307'),
 ('14865487', '1827656', '192307'),
 ('15959050', '5324258', '192307'),
 ('14624189', '1827275', '192307'),
 ('14624190', '1827275', '192307'),
 ('14624191', '1827275', '192307'),
 ('15588223', '1827275', '192307'),
 ('15852254', '1624125', '192307'),
 ('19517530', '1624125', '192307'),
 ('9710002', '1827294', '192307'),
 ('9710003', '1827294', '192307'),
 ('9710055', '1827294', '192307'),
 ('9710098', '1827294', '192307'),
 ('9710638', '1827294', '192307'),
 ('9710639', '1827294', '192307'),
 ('13829626', '1827294', '192307'),
 ('13829627', '1827294', '192307'),
 ('13829628', '1827294', '192307'),
 ('13830796', '1827377', '192307'),
 ('13844300', '1827377', '192307'),
 ('6251938', '19556630', '192778'),
 ('6251938', '19556728', '192778'),
 ('19591107', '3401811', '192778'),
 ('19591288', '3401811', '192778'),
 ('19591288', '3402447', '192778'),
 ('19591107', '19553251', '192778'),
 ('19591124', '19553251', '192778'),
 ('19591124', '19553157', '192778'),
 ('9094108', '13376017', '184818'),
 ('9094108', '13376035', '184818'),
 ('9094108', '13376032', '184818'),
 ('9094108', '13376033', '184818'),
 ('184877', '184843', '184843'),
 ('11018284', '184877', '184843'),
 ('11018286', '184877', '184843'),
 ('11018288', '184877', '184843'),
 ('11018289', '184877', '184843'),
 ('11018388', '184877', '184843'),
 ('11018389', '184877', '184843'),
 ('11018390', '184877', '184843'),
 ('11018391', '184877', '184843'),
 ('11018392', '184877', '184843'),
 ('11018394', '184877', '184843'),
 ('11018395', '184877', '184843'),
 ('11019277', '184877', '184843'),
 ('11019278', '184877', '184843'),
 ('11019280', '184877', '184843'),
 ('11019281', '184877', '184843'),
 ('11019283', '184877', '184843'),
 ('11019284', '184877', '184843'),
 ('11019285', '184877', '184843'),
 ('11019287', '184877', '184843'),
 ('11019288', '184877', '184843'),
 ('11019290', '184877', '184843'),
 ('11019357', '184877', '184843'),
 ('11021024', '184877', '184843'),
 ('11021025', '184877', '184843'),
 ('11021024', '7231014', '184843'),
 ('2060182', '192758', '192758'),
 ('16096444', '3513418', '72596'),
 ('6950744', '3438257', '72596'),
 ('6950744', '3438258', '72596'),
 ('16096444', '3513419', '72596'),
 ('12835558', '3466560', '72596'),
 ('12835558', '3579430', '72596'),
 ('19138507', '3407300', '72596'),
 ('11833993', '3407307', '72596'),
 ('11833993', '3407315', '72596'),
 ('19138507', '3407301', '72596'),
 ('2632179', '3563750', '72596'),
 ('2632179', '4308665', '72596'),
 ('18502755', '3490913', '72596'),
 ('18502755', '3490910', '72596'),
 ('17483459', '5606523', '114686'),
 ('17483459', '5605714', '114686'),
 ('19383581', '5605714', '114686'),
 ('17483459', '5605960', '114686'),
 ('17483459', '5606683', '114686'),
 ('19383581', '5606683', '114686'),
 ('17483459', '5605905', '114686'),
 ('17483459', '5606536', '114686'),
 ('17483459', '5606640', '114686'),
 ('17483459', '5605721', '114686'),
 ('17483459', '5605835', '114686'),
 ('1391372', '5999749', '114686'),
 ('1391372', '6000176', '114686'),
 ('1391397', '5999601', '114686'),
 ('1391345', '5999659', '114686'),
 ('1391345', '6000173', '114686'),
 ('1391389', '6000191', '114686'),
 ('1391397', '6000191', '114686'),
 ('1391389', '5999764', '114686'),
 ('17353399', '6037727', '114686'),
 ('17353399', '6037700', '114686'),
 ('17238940', '6037711', '114686'),
 ('17238940', '6037860', '114686'),
 ('4062443', '5605767', '114686'),
 ('4063336', '5605767', '114686'),
 ('3230465', '5605874', '114686'),
 ('3230465', '5606178', '114686'),
 ('4062443', '5606178', '114686'),
 ('4063336', '5606178', '114686'),
 ('4609797', '4525097', '114686'),
 ('5349516', '4525097', '114686'),
 ('5365364', '4525097', '114686'),
 ('5413417', '4525097', '114686'),
 ('4609797', '4525109', '114686'),
 ('4844942', '4525109', '114686'),
 ('4844942', '4555887', '114686'),
 ('5349509', '4537017', '114686'),
 ('5365364', '4537017', '114686'),
 ('5349509', '4537023', '114686'),
 ('5349516', '4537023', '114686'),
 ('5413417', '4537023', '114686'),
 ('6333788', '5961522', '114686'),
 ('6418289', '5961522', '114686'),
 ('6418289', '5961578', '114686'),
 ('6333788', '5961579', '114686'),
 ('6333674', '5961507', '114686'),
 ('6333674', '5961572', '114686'),
 ('5996508', '5996486', '50371'),
 ('18997125', '5996486', '50371'),
 ('5996508', '1908810', '50371'),
 ('18997125', '1908810', '50371'),
 ('5996509', '5996485', '50371'),
 ('5996514', '5996485', '50371'),
 ('5996522', '5996485', '50371'),
 ('5996531', '5996485', '50371'),
 ('5996552', '5996485', '50371'),
 ('14006889', '5996485', '50371'),
 ('14007121', '5996485', '50371'),
 ('14035206', '5996485', '50371'),
 ('14039305', '5996485', '50371'),
 ('14039309', '5996485', '50371'),
 ('17826180', '5996485', '50371'),
 ('17945417', '5996485', '50371'),
 ('18915910', '5996485', '50371'),
 ('5996514', '9399860', '50371'),
 ('5996531', '9399860', '50371'),
 ('5996552', '9399860', '50371'),
 ('18915910', '9399860', '50371'),
 ('5996509', '9399861', '50371'),
 ('5996522', '9399861', '50371'),
 ('14006889', '9399861', '50371'),
 ('14007121', '9399861', '50371'),
 ('14035206', '9399861', '50371'),
 ('14039305', '9399861', '50371'),
 ('14039309', '9399861', '50371'),
 ('17826180', '9399861', '50371'),
 ('17945417', '9399861', '50371'),
 ('7578957', '2505635', '192734'),
 ('7890421', '2505635', '192734'),
 ('7578957', '5488132', '192734'),
 ('7890421', '5488132', '192734'),
 ('17207121', '2663937', '49715'),
 ('17207121', '2533323', '49715'),
 ('16822778', '2218246', '49715'),
 ('16822778', '2429557', '49715'),
 ('72639', '60189', '60189'),
 ('1574364', '60189', '60189'),
 ('3788485', '60189', '60189'),
 ('391133', '176095', '60189'),
 ('181165', '51490', '60189'),
 ('1574582', '72639', '60189'),
 ('1590251', '72639', '60189'),
 ('1754552', '72639', '60189'),
 ('1754553', '72639', '60189'),
 ('1754554', '72639', '60189'),
 ('1754555', '72639', '60189'),
 ('1754556', '72639', '60189'),
 ('1754557', '72639', '60189'),
 ('1754558', '72639', '60189'),
 ('1754559', '72639', '60189'),
 ('1754560', '72639', '60189'),
 ('1754561', '72639', '60189'),
 ('1754562', '72639', '60189'),
 ('1754564', '72639', '60189'),
 ('3826844', '72639', '60189'),
 ('3826845', '72639', '60189'),
 ('3826847', '72639', '60189'),
 ('3826848', '72639', '60189'),
 ('3826851', '72639', '60189'),
 ('3826854', '72639', '60189'),
 ('3826856', '72639', '60189'),
 ('3826860', '72639', '60189'),
 ('3826864', '72639', '60189'),
 ('3826882', '72639', '60189'),
 ('3826900', '72639', '60189'),
 ('19161849', '72639', '60189'),
 ('19161871', '72639', '60189'),
 ('19161924', '72639', '60189'),
 ('19161954', '72639', '60189'),
 ('19162030', '72639', '60189'),
 ('19162067', '72639', '60189'),
 ('19162084', '72639', '60189'),
 ('19162115', '72639', '60189'),
 ('19162129', '72639', '60189'),
 ('19261230', '72639', '60189'),
 ('181165', '81995', '60189'),
 ('2031968', '72195', '60189'),
 ('2031968', '72196', '60189'),
 ('391133', '337422', '60189'),
 ('4537555', '1858720', '60189'),
 ('2865249', '19161924', '60189'),
 ('4632920', '19161924', '60189'),
 ('4632921', '19161924', '60189'),
 ('4632922', '19161924', '60189'),
 ('4632923', '19161924', '60189'),
 ('4632924', '19161924', '60189'),
 ('4632925', '19161924', '60189'),
 ('4632926', '19161924', '60189'),
 ('4632927', '19161924', '60189'),
 ('4632928', '19161924', '60189'),
 ('4632929', '19161924', '60189'),
 ('4634580', '19161924', '60189'),
 ('4634581', '19161924', '60189'),
 ('4634582', '19161924', '60189'),
 ('4634583', '19161924', '60189'),
 ('4634584', '19161924', '60189'),
 ('4634585', '19161924', '60189'),
 ('4634586', '19161924', '60189'),
 ('4634587', '19161924', '60189'),
 ('4634588', '19161924', '60189'),
 ('4634589', '19161924', '60189'),
 ('4634590', '19161924', '60189'),
 ('4634591', '19161924', '60189'),
 ('4634592', '19161924', '60189'),
 ('4634593', '19161924', '60189'),
 ('4634594', '19161924', '60189'),
 ('4634595', '19161924', '60189'),
 ('4634596', '19161924', '60189'),
 ('4634597', '19161924', '60189'),
 ('4634598', '19161924', '60189'),
 ('4634599', '19161924', '60189'),
 ('4634600', '19161924', '60189'),
 ('4634601', '19161924', '60189'),
 ('4634613', '19161924', '60189'),
 ('8337869', '19161924', '60189'),
 ('4636132', '19162030', '60189'),
 ('4636133', '19162030', '60189'),
 ('4636134', '19162030', '60189'),
 ('4636135', '19162030', '60189'),
 ('4636136', '19162030', '60189'),
 ('4636137', '19162030', '60189'),
 ('4636138', '19162030', '60189'),
 ('4636139', '19162030', '60189'),
 ('4636140', '19162030', '60189'),
 ('4636141', '19162030', '60189'),
 ('4636142', '19162030', '60189'),
 ('4636143', '19162030', '60189'),
 ('4636144', '19162030', '60189'),
 ('4636145', '19162030', '60189'),
 ('4636146', '19162030', '60189'),
 ('4636147', '19162030', '60189'),
 ('4636148', '19162030', '60189'),
 ('4638811', '19162030', '60189'),
 ('4638812', '19162030', '60189'),
 ('4638813', '19162030', '60189'),
 ('4638814', '19162030', '60189'),
 ('4638815', '19162030', '60189'),
 ('4638816', '19162030', '60189'),
 ('4638817', '19162030', '60189'),
 ('4638818', '19162030', '60189'),
 ('4638819', '19162030', '60189'),
 ('4638820', '19162030', '60189'),
 ('4638821', '19162030', '60189'),
 ('4638822', '19162030', '60189'),
 ('4638823', '19162030', '60189'),
 ('4638824', '19162030', '60189'),
 ('4638825', '19162030', '60189'),
 ('4638826', '19162030', '60189'),
 ('4638827', '19162030', '60189'),
 ('4638828', '19162030', '60189'),
 ('8337853', '19162030', '60189'),
 ('8337854', '19162030', '60189'),
 ('2865249', '1590251', '60189'),
 ('4632920', '1590251', '60189'),
 ('4632921', '1590251', '60189'),
 ('4632922', '1590251', '60189'),
 ('4632923', '1590251', '60189'),
 ('4632924', '1590251', '60189'),
 ('4632925', '1590251', '60189'),
 ('4632926', '1590251', '60189'),
 ('4632927', '1590251', '60189'),
 ('4632928', '1590251', '60189'),
 ('4632929', '1590251', '60189'),
 ('4636132', '1754559', '60189'),
 ('4636133', '1754559', '60189'),
 ('4636134', '1754559', '60189'),
 ('4636135', '1754559', '60189'),
 ('4636136', '1754559', '60189'),
 ('4636137', '1754559', '60189'),
 ('4636138', '1754559', '60189'),
 ('4636139', '1754559', '60189'),
 ('4636140', '1754559', '60189'),
 ('4636141', '1754559', '60189'),
 ('4636142', '1754559', '60189'),
 ('4636143', '1754559', '60189'),
 ('4636144', '1754559', '60189'),
 ('4636145', '1754559', '60189'),
 ('4636146', '1754559', '60189'),
 ('4636147', '1754559', '60189'),
 ('4636148', '1754559', '60189'),
 ('4633166', '1754560', '60189'),
 ('4633167', '1754560', '60189'),
 ('4633168', '1754560', '60189'),
 ('4633169', '1754560', '60189'),
 ('4633170', '1754560', '60189'),
 ('4633171', '1754560', '60189'),
 ('4633172', '1754560', '60189'),
 ('4633173', '1754560', '60189'),
 ('4633174', '1754560', '60189'),
 ('4633175', '1754560', '60189'),
 ('4633176', '1754560', '60189'),
 ('4633177', '1754560', '60189'),
 ('4634580', '1754561', '60189'),
 ('4634581', '1754561', '60189'),
 ('4634582', '1754561', '60189'),
 ('4634583', '1754561', '60189'),
 ('4634584', '1754561', '60189'),
 ('4634585', '1754561', '60189'),
 ('4634586', '1754561', '60189'),
 ('4634587', '1754561', '60189'),
 ('4634588', '1754561', '60189'),
 ('4634589', '1754561', '60189'),
 ('4634590', '1754561', '60189'),
 ('4634591', '1754561', '60189'),
 ('4634592', '1754561', '60189'),
 ('4634593', '1754561', '60189'),
 ('4634594', '1754561', '60189'),
 ('4634595', '1754561', '60189'),
 ('4634596', '1754561', '60189'),
 ('4634597', '1754561', '60189'),
 ('4634598', '1754561', '60189'),
 ('4634599', '1754561', '60189'),
 ('4634600', '1754561', '60189'),
 ('4634601', '1754561', '60189'),
 ('4634613', '1754561', '60189'),
 ('8337869', '1754561', '60189'),
 ('4633166', '19162067', '60189'),
 ('4633167', '19162067', '60189'),
 ('4633168', '19162067', '60189'),
 ('4633169', '19162067', '60189'),
 ('4633170', '19162067', '60189'),
 ('4633171', '19162067', '60189'),
 ('4633172', '19162067', '60189'),
 ('4633173', '19162067', '60189'),
 ('4633174', '19162067', '60189'),
 ('4633175', '19162067', '60189'),
 ('4633176', '19162067', '60189'),
 ('4633177', '19162067', '60189'),
 ('4635758', '19162067', '60189'),
 ('4635759', '19162067', '60189'),
 ('4635760', '19162067', '60189'),
 ('4635761', '19162067', '60189'),
 ('4635762', '19162067', '60189'),
 ('4635763', '19162067', '60189'),
 ('4635764', '19162067', '60189'),
 ('4635765', '19162067', '60189'),
 ('4635766', '19162067', '60189'),
 ('4635767', '19162067', '60189'),
 ('4635768', '19162067', '60189'),
 ('4635769', '19162067', '60189'),
 ('18555473', '19162067', '60189'),
 ('4648134', '1754557', '60189'),
 ('4648135', '1754557', '60189'),
 ('4648136', '1754557', '60189'),
 ('4648137', '1754557', '60189'),
 ('4648138', '1754557', '60189'),
 ('4648139', '1754557', '60189'),
 ('4648140', '1754557', '60189'),
 ('4648141', '1754557', '60189'),
 ('4648142', '1754557', '60189'),
 ('4648143', '1754557', '60189'),
 ('4648144', '1754557', '60189'),
 ('4648145', '1754557', '60189'),
 ('4648146', '1754557', '60189'),
 ('4648147', '1754557', '60189'),
 ('4648148', '1754557', '60189'),
 ('4648149', '1754557', '60189'),
 ('4648150', '1754557', '60189'),
 ('4648151', '1754557', '60189'),
 ('4648152', '1754557', '60189'),
 ('4648153', '1754557', '60189'),
 ('4648154', '1754557', '60189'),
 ('4648164', '1754557', '60189'),
 ('4648165', '1754557', '60189'),
 ('4648166', '1754557', '60189'),
 ('4648167', '1754557', '60189'),
 ('7151412', '1754557', '60189'),
 ('7949967', '1754557', '60189'),
 ('4639330', '19161849', '60189'),
 ('4639331', '19161849', '60189'),
 ('4639332', '19161849', '60189'),
 ('4639333', '19161849', '60189'),
 ('4639334', '19161849', '60189'),
 ('4639335', '19161849', '60189'),
 ('4639336', '19161849', '60189'),
 ('4639337', '19161849', '60189'),
 ('4639338', '19161849', '60189'),
 ('4639339', '19161849', '60189'),
 ('4639340', '19161849', '60189'),
 ('4639341', '19161849', '60189'),
 ('4639342', '19161849', '60189'),
 ('4639343', '19161849', '60189'),
 ('4639344', '19161849', '60189'),
 ('4639345', '19161849', '60189'),
 ('4639346', '19161849', '60189'),
 ('4639347', '19161849', '60189'),
 ('4639348', '19161849', '60189'),
 ('4649594', '19161849', '60189'),
 ('4649595', '19161849', '60189'),
 ('4649596', '19161849', '60189'),
 ('4649597', '19161849', '60189'),
 ('4649598', '19161849', '60189'),
 ('4649599', '19161849', '60189'),
 ('4649600', '19161849', '60189'),
 ('4649601', '19161849', '60189'),
 ('4649602', '19161849', '60189'),
 ('4649603', '19161849', '60189'),
 ('4649604', '19161849', '60189'),
 ('4649605', '19161849', '60189'),
 ('4649606', '19161849', '60189'),
 ('4649607', '19161849', '60189'),
 ('4649608', '19161849', '60189'),
 ('4649609', '19161849', '60189'),
 ('4649610', '19161849', '60189'),
 ('4649611', '19161849', '60189'),
 ('4649612', '19161849', '60189'),

### * select ents and run test

In [45]:
dups_test_processed = tgm.load(os.path.join(os.getcwd(), "../data/tests results/osm duplicates test", "dups_test_processed.pkl"))
print(len(dups_test_processed))

1634

In [44]:
print('dups_df: ', len(dups_df))
print('dups_test_processed: ', len(dups_test_processed))
to_test = dups_df[['id', 'tags.parent_id','tags.country_id']].apply(tuple, axis=1).isin(dups_test_processed)
to_test = dups_df[~to_test]
print(len(to_test))
# to_test = list(to_test.groupby('tags.country_id'))
print(len(to_test))
# to_test = to_test[:2]
# print(len(to_test))

dups_df:  1636
dups_test_processed:  0
1636
1636

In [40]:
def apply_to_group(df):
    country_name = df.iloc[0]['tags.country_name']
    path = os.path.join(os.getcwd(), r"..\data\tests results\osm duplicates test", country_name, f"{country_name}_dups_test_res.pkl")
    osmt.osm_test_center(
    df,
    save_temp=True,
    save_path=path
    )

In [ ]:
# [OLD]
# to_test.groupby('tags.country_id').apply(apply_to_group)

[INFO] :  ^ [2/2]: testing ('6543282', '6543273', '192756'):
[INFO] :    > Getting admin_centre:
[INFO] :     * Found node (admin_centre)
[INFO] :    > Testing admin_centre node (id: 7934379969)
[INFO] :     * Finished testing (admin_centre): True
[INFO] :    > Getting label:
[INFO] :     * Missing node (label)
[INFO] :    > Getting place:
[INFO] :     * Found node (place)
[INFO] :    > Testing place node (id: 7934379969)
[INFO] :     * Finished testing (place): True
[INFO] :    > Getting geom_node:
[INFO] :     * Found node (geom_node)
[INFO] :    > Testing geom_node node (id: 4298631214)
[INFO] :     * Finished testing (geom_node): True
[INFO] :    > Getting centroid:
[INFO] :     * Found node (centroid)
[INFO] :    > Testing centroid (lat: 36.8944071, lon: 6.4872707)
[INFO] :     * Finished testing (centroid): False
[INFO] :   * saving ...
[INFO] :  $ finished: status: {'admin_centre': 'ok', 'label': 'missing', 'place': 'ok', 'geom_node': 'ok', 'centroid': 'ok'}
C:\Users\gonta\AppData\Local\Temp\ipykernel_8368\2808598228.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  to_test.groupby('tags.country_id',group_keys=True).apply(apply_to_group)

Empty DataFrame
Columns: []
Index: []

In [53]:
for key, group in to_test:
    apply_to_group(group)

[INFO] :  ^ [2/2]: testing ('18305258', '19377767', '49915'):
[INFO] :    > Getting admin_centre:
[INFO] :     * Missing node (admin_centre)
[INFO] :    > Getting label:
[INFO] :     * Missing node (label)
[INFO] :    > Getting place:
[INFO] :     * Missing node (place)
[INFO] :    > Getting geom_node:
[INFO] :     * Missing node (geom_node)
[INFO] :    > Getting centroid:
[INFO] :     * Missing node (centroid)
[INFO] :   * saving ...
[INFO] :  $ finished: status: {'admin_centre': 'missing', 'label': 'missing', 'place': 'missing', 'geom_node': 'missing', 'centroid': 'missing'}

### * update processed data

In [48]:
path_obj = Path(os.path.join(os.getcwd(), "../data/tests results/osm duplicates test"))
test_res_list = [tgm.load(file) for file in list(path_obj.rglob('*/*.pkl'))]
test_res = {}
for d in test_res_list:
    test_res.update(d)
print(len(test_res))

del test_res_list

1636

In [ ]:
# test_res = tgm.load(os.path.join(os.getcwd(), "../data/tests results/osm duplicates test", "dups_test_res.pkl"))
# print(len(test_res))

2

In [57]:
dups_test_processed = set()
for tuple_id, res in test_res.items():
    if 'ok' in [ele['status'] for ele in res.values()]:
        dups_test_processed.add(tuple_id)
print(len(dups_test_processed))

1634

In [44]:
tgm.dump(os.path.join(os.getcwd(), "../data/tests results/osm duplicates test", "dups_test_processed.pkl"), dups_test_processed)

### * review

In [18]:
path_obj = Path(os.path.join(os.getcwd(), "../data/tests results/osm duplicates test"))
test_res_list = [tgm.load(file) for file in list(path_obj.rglob('*/*.pkl'))]
test_res = {}
for d in test_res_list:
    test_res.update(d)
print(len(test_res))

del test_res_list

1636

In [19]:
result_status = [[[k,v['status']] for k,v in ele.items()] for ele in test_res.values()]
pd.Series(list(result_status)).value_counts()

[[admin_centre, ok], [label, missing], [place, ok], [geom_node, ok], [centroid, ok]]                        1399
[[admin_centre, missing], [label, missing], [place, missing], [geom_node, ok], [centroid, ok]]               154
[[admin_centre, missing], [label, ok], [place, ok], [geom_node, ok], [centroid, ok]]                          55
[[admin_centre, ok], [label, ok], [place, ok], [geom_node, ok], [centroid, ok]]                               20
[[admin_centre, missing], [label, missing], [place, ok], [geom_node, ok], [centroid, ok]]                      6
[[admin_centre, missing], [label, missing], [place, missing], [geom_node, missing], [centroid, missing]]       2
Name: count, dtype: int64

In [20]:
pd.Series([ele[1] for lis in result_status for ele in lis]).value_counts()

ok         6242
missing    1938
Name: count, dtype: int64

### * select false entities and childs to delete

In [21]:
test_res_simplified = {}
for id, val in test_res.items():
    true_count = 0
    false_count = 0
    for type in ['admin_centre', 'label', 'place', 'geom_node', 'centroid']:
        if val[type]['status'] == 'ok':
            # select the first one that gives True
            # test_res_simplified[id] = False
            # if val[type]['result'] is True:
            #     test_res_simplified[id] = val[type]['result']
            #     break

            # assign the first valid result
            # test_res_simplified[id] = val[type]['result']
            # break

            # make a voting weight selection
            if val[type]['result'] is True: true_count += 1
            else: false_count += 1
    
    test_res_simplified[id] = true_count >= false_count


pd.Series([v for k,v in test_res_simplified.items()]).value_counts()

True     1518
False     118
Name: count, dtype: int64

In [69]:
dups_tuples_to_delete_parents = [k for k,v in test_res_simplified.items() if v is False]
print(len(dups_tuples_to_delete_parents))

118

In [73]:
dups_tuples_to_delete_parents

[('14326718', '3921322', '184640'),
 ('59190', '59752', '59065'),
 ('5598639', '70802', '59065'),
 ('8030910', '70802', '59065'),
 ('416271', '4217435', '52411'),
 ('7400', '53134', '52411'),
 ('1561101', '7400', '52411'),
 ('117571', '416271', '52411'),
 ('13482954', '12171907', '184629'),
 ('406273', '325866', '59470'),
 ('2662005', '334443', '59470'),
 ('2662004', '332924', '59470'),
 ('4283101', '3759431', '186382'),
 ('4283101', '3759439', '186382'),
 ('17755316', '3759439', '186382'),
 ('4283101', '3759447', '186382'),
 ('4283101', '3759438', '186382'),
 ('4283101', '3759448', '186382'),
 ('4283101', '3759427', '186382'),
 ('17755317', '3759427', '186382'),
 ('17755318', '3759427', '186382'),
 ('17759455', '3759427', '186382'),
 ('1980749', '153549', '167454'),
 ('7128807', '1310024', '120027'),
 ('11908912', '1342117', '120027'),
 ('11919498', '1342124', '120027'),
 ('18963551', '1343276', '120027'),
 ('11909897', '1438574', '120027'),
 ('11909898', '1438574', '120027'),
 ('13466581', '1314678', '120027'),
 ('62442', '62771', '51477'),
 ('3659532', '62372', '51477'),
 ('62673', '62761', '51477'),
 ('1115033', '62586', '51477'),
 ('1115034', '62586', '51477'),
 ('1818486', '62442', '51477'),
 ('155567', '62673', '51477'),
 ('1808583', '62597', '51477'),
 ('223136', '192307', '192307'),
 ('5324202', '223136', '192307'),
 ('11991949', '956611', '192307'),
 ('6251938', '19556728', '192778'),
 ('19591107', '3401811', '192778'),
 ('19591288', '3401811', '192778'),
 ('19591288', '3402447', '192778'),
 ('19591107', '19553251', '192778'),
 ('19591124', '19553251', '192778'),
 ('19591124', '19553157', '192778'),
 ('9094108', '13376035', '184818'),
 ('9094108', '13376033', '184818'),
 ('184877', '184843', '184843'),
 ('11021024', '7231014', '184843'),
 ('16096444', '3513418', '72596'),
 ('6950744', '3438257', '72596'),
 ('12835558', '3579430', '72596'),
 ('11833993', '3407307', '72596'),
 ('19138507', '3407301', '72596'),
 ('2632179', '3563750', '72596'),
 ('18502755', '3490910', '72596'),
 ('17483459', '5606523', '114686'),
 ('17483459', '5605714', '114686'),
 ('19383581', '5605714', '114686'),
 ('17483459', '5605960', '114686'),
 ('17483459', '5606683', '114686'),
 ('17483459', '5605905', '114686'),
 ('17483459', '5606536', '114686'),
 ('17483459', '5606640', '114686'),
 ('17483459', '5605835', '114686'),
 ('1391372', '6000176', '114686'),
 ('1391397', '5999601', '114686'),
 ('1391345', '6000173', '114686'),
 ('1391389', '5999764', '114686'),
 ('17353399', '6037727', '114686'),
 ('17238940', '6037711', '114686'),
 ('4062443', '5605767', '114686'),
 ('3230465', '5605874', '114686'),
 ('4063336', '5606178', '114686'),
 ('5349516', '4525097', '114686'),
 ('5413417', '4525097', '114686'),
 ('4609797', '4525109', '114686'),
 ('4844942', '4555887', '114686'),
 ('6333788', '5961522', '114686'),
 ('6418289', '5961578', '114686'),
 ('6333674', '5961572', '114686'),
 ('18997125', '5996486', '50371'),
 ('5996508', '1908810', '50371'),
 ('5996514', '9399860', '50371'),
 ('5996531', '9399860', '50371'),
 ('5996552', '9399860', '50371'),
 ('5996509', '9399861', '50371'),
 ('7890421', '5488132', '192734'),
 ('181165', '81995', '60189'),
 ('2031968', '72195', '60189'),
 ('4537555', '1858720', '60189'),
 ('3030949', '1754564', '60189'),
 ('3030949', '19162084', '60189'),
 ('4785725', '1760242', '60189'),
 ('2121878', '367666', '60189'),
 ('4525435', '1442695', '60189'),
 ('3369629', '1157620', '60189'),
 ('1683364', '373332', '51701'),
 ('2060182', '192757', '192757'),
 ('4496067', '174737', '174737'),
 ('5324202', '223136', '174737'),
 ('11629050', '1211496', '174737'),
 ('11628545', '1211488', '174737'),
 ('3030949', '1754564', '60199'),
 ('3030949', '19162084', '60199'),
 ('358021', '58447', '62149'),
 ('57539', '58437', '62149'),
 ('19415099', '1902967', '49915'),
 ('12138923', '19539163', '49915'),
 ('12138923', '19539228', '49915'),
 ('13470001', '19539159', '49915'),
 ('13470001', '19539161', '49915'),
 ('12138923', '19539173', '49915'),
 ('12138923', '19539197', '49915'),
 ('13470001', '19539198', '49915')]

In [104]:
temp = [[ele[0],ele[2]] for ele in dups_tuples_to_delete_parents]
dups_tuples_to_delete_childs = [ele for ele in all_id_tuples if [ele[1],ele[2]] in temp]
print(len(dups_tuples_to_delete_childs))

# dups_tuples_to_delete = dups_tuples_to_delete_childs + dups_tuples_to_delete_parents
dups_tuples_to_delete = dups_tuples_to_delete_parents
print(len(dups_tuples_to_delete))

923
118

In [105]:
tgm.dump(os.path.join(os.getcwd(), "../data/tests results/osm duplicates test", "dups_tuples_to_delete.pkl"), dups_tuples_to_delete)

### * add manual review deletion

In [106]:
to_review_ids = tgm.load(os.path.join(os.getcwd(), "../data/tests results/osm duplicates test", "to_review_ids.pkl"))
print(len(to_review_ids))

6

In [116]:
to_review_ids

[('72639', '60189', '60189'),
 ('72639', '60199', '60199'),
 ('6543282', '6543265', '192756'),
 ('6543282', '6543273', '192756'),
 ('59190', '59195', '59065'),
 ('59190', '59752', '59065')]

In [115]:
[[k,v['result']] for k,v in test_res[('6543282', '6543265', '192756')].items()]

[['admin_centre', False],
 ['label', None],
 ['place', False],
 ['geom_node', True],
 ['centroid', True]]

In [110]:
manual_dups_tuples_to_delete = [('6543282', '6543273', '192756'), ('59190', '59195', '59065')]

In [111]:
tgm.dump(os.path.join(os.getcwd(), "../data/tests results/osm duplicates test", "manual_dups_tuples_to_delete.pkl"), manual_dups_tuples_to_delete)

In [112]:
dups_tuples_to_delete = dups_tuples_to_delete + manual_dups_tuples_to_delete
print(len(dups_tuples_to_delete))

120

In [113]:
tgm.dump(os.path.join(os.getcwd(), "../data/tests results/osm duplicates test", "dups_tuples_to_delete.pkl"), dups_tuples_to_delete)

In [129]:
print(len(dups_id_tuples))
print(len(dups_tuples_to_delete))
temp = tgm.complement(dups_id_tuples, dups_tuples_to_delete)
print(len(temp))

1636
120
1516