# Init

In [ ]:
# init
from importlib import reload
from pathlib import Path
import os
import sys
import pandas as pd

sys.path.append('..')
sys.path.append("C:/Users/gonta/D/software developer/packages")
import toolsGeneral.main as tgm
import toolsPandas.helpers as tph

def reloadPckg():
    reload(tgm)
    reload(tph)

# Review

In [17]:
dir = Path(os.path.join(os.getcwd(), '..', 'data/fixed'))
df_by_cntr_fixed = {
    file.parent.name:tgm.load(str(file))
    for file in [f for f in dir.rglob('*/*.pkl')]
}
len(df_by_cntr_fixed)

64

In [18]:
df_all = pd.concat(df_by_cntr_fixed.values(), ignore_index=True)
print(len(df_all))

117697

In [19]:
df_all['tags.admin_level'].value_counts()

tags.admin_level
8    98392
6    18241
4     1000
2       64
Name: count, dtype: Int64

In [20]:
df_all['tags.parent_id'].map(lambda arg: 'Missing' if pd.isna(arg) else type(arg)).value_counts()

tags.parent_id
<class 'str'>    117633
Missing              64
Name: count, dtype: int64

In [21]:
def resume_divisions(rls : dict):
    resume = {}
    for k,df in rls.items():
        add_1 = df[df['tags.admin_level'] == '4']
        add_2 = df[df['tags.admin_level'] == '6']
        add_3 = df[df['tags.admin_level'] == '8']
        resume[k] = {'add_1': add_1, 'add_2': add_2, 'add_3': add_3}
    
    return pd.DataFrame(resume)

In [22]:
resume = resume_divisions(df_by_cntr_fixed)
len(resume)

3

In [23]:
tph.df_peek(resume[['Colombia']].T.map(len))

In [6]:
tph.df_peek(resume[['Colombia']].T.map(lambda arg: arg['tags.name'].to_list()))

# Select what to add

In [24]:
tph.df_peek(resume[list(df_by_cntr_fixed.keys())].T.map(len))

In [25]:
df_by_cntr_to_add = {}
for k,df in df_by_cntr_fixed.items():
    lvl1 = df[df['tags.admin_level'] == '4']
    if not lvl1.empty:
        df_by_cntr_to_add[k] = df
print(len(df_by_cntr_to_add))

54

In [26]:
tph.df_peek(resume[list(df_by_cntr_to_add.keys())].T.map(len))

# Make add tree

# 1. rels_data_index

In [27]:
rels_index = {row['id']:row.to_dict() for df in df_by_cntr_to_add.values() for i,row in df.iterrows()}
len(rels_index)

117256

In [28]:
rels_index['10001851']

{'type': 'rel',
 'id': '10001851',
 'tags.admin_level': '8',
 'tags.parent_id': '3407319',
 'tags.name': 'Kriaučiūnai',
 'tags.name:en': None,
 'tags.alt_name:en': None,
 'tags.ISO3166-1': None,
 'tags.ISO3166-2': None,
 'tags.is_in:country': None,
 'tags.ref:nuts': None,
 'tags.ref:nuts:2': None,
 'tags.ref:nuts:3': None,
 'tags.addr:country': None,
 'tags.country_name': 'Lithuania',
 'tags.country_id': '72596'}

In [29]:
tgm.dump(os.path.join(os.getcwd(), "../data/final", "rels_index.pkl"), rels_index)

## 2. childs_index

In [ ]:
childs_index = {}
for ele_id, vals in rels_index.items():
    parent_id = vals['tags.parent_id']
    if parent_id is not None:
        childs = childs_index.get(parent_id, [])
        childs.append(ele_id)
        childs_index[parent_id] = childs

In [32]:
tgm.dump(os.path.join(os.getcwd(), "../data/final", "childs_index.pkl"), childs_index)

## 3. make json tree by country and save

In [75]:
def make_tree_level(rels_ids):
    level = []
    for id in rels_ids:
        rel_data = rels_index[id]
        text_candidates = [
            rel_data.get('tags.name:en'),
            rel_data.get('tags.alt_name:en'), 
            rel_data.get('tags.name')]
        for text in text_candidates:
            if text:
                level.append({
                    'id': rel_data['id'],
                    'text': text,
                    'children': make_tree_level(childs_index.get(id, []))
                })
                break
    return level

In [76]:
lvl0_ids = []
for k,v in rels_index.items():
    if v['tags.admin_level'] == '2':
        lvl0_ids.append(k)

In [84]:
tree = make_tree_level(lvl0_ids)
print(len(tree))

54

In [92]:
import json
for country_tree in tree:
    country_path = os.path.join(os.getcwd(), "../data/final/add_tree", f"{country_tree['text']}.json")
    if not os.path.exists(os.path.dirname(country_path)):
        os.makedirs(os.path.dirname(country_path))
    with open(country_path, "w", encoding="utf-8") as f:
        json.dump(country_tree, f, indent=2)

## 4. add old tree

In [96]:
old_add_tree = tgm.load(r"C:\Users\gonta\D\study\full stack\projects\administrative divisions\src\allAddTree.json")
print(len(old_add_tree))

5

In [98]:
for country_tree in old_add_tree:
    country_path = os.path.join(os.getcwd(), "../data/final/add_tree", f"{country_tree['text']}.json")
    if not os.path.exists(os.path.dirname(country_path)):
        os.makedirs(os.path.dirname(country_path))
    with open(country_path, "w", encoding="utf-8") as f:
        json.dump(country_tree, f, indent=2)

## 5. join add trees

In [105]:
dataDir = Path(os.path.join(os.getcwd(), '..', 'data', 'final', 'add_tree'))
rawFiles = [f for f in dataDir.rglob('*.json')]
all_add_tree = [tgm.load(file) for file in rawFiles]
print(len(all_add_tree))

58

In [104]:
all_add_tree_path = os.path.join(os.getcwd(), "../data/final/allAddTree.json")
with open(all_add_tree_path, "w", encoding="utf-8") as f:
        json.dump(all_add_tree, f, indent=2)