In [45]:
# init
import requests
import pickle
from pathlib import Path
from importlib import reload
import toolsGeneral.main as tgm
import toolsPandas.helpers as tph
import os
import boto3
import pandas as pd
import copy

import shutil

def pckgs_reload():
    reload(tgm)
    reload(tph)

ROOT = Path.cwd().parents[0]
DATA_DIR = ROOT / "data"
SCRAPE_DIR = DATA_DIR / 'raw/osm countries queries'

## Review state of tasks

In [46]:
process_state = tgm.load(DATA_DIR / 'process_state.json')
print(len(process_state))

task_state = {
    'scrape':{'dir':'data/raw/osm countries queries', 'required_task':'scrape'},
    'clean':{'dir':'data/cleaned', 'required_task':'scrape'},
    'test_basic':{'dir':'data/tests results/osm basic test','required_task':'clean'}
}

tasks = ['scrape', 'clean', 'test_basic']
for task in tasks:
    task_path = ROOT / task_state[task]['dir']
    ok = [c for c, val in process_state.items() if (val[task]['status'] in ['ok', 'error'])]
    pending = [c for c, val in process_state.items() if (val[task]['status'] in ['pending', 'error'])]
    countries_dirs = [dir.relative_to(task_path).name for dir in task_path.glob('*') if dir.is_dir()]
    
    task_state[task]['ok'] = ok
    task_state[task]['pending'] = pending
    previous_task_ok = task_state[task_state[task]['required_task']]['ok']
    task_state[task]['to_process'] = tgm.complement(previous_task_ok, ok)
    task_state[task]['local_dirs'] = countries_dirs
    task_state[task]['ok_wihout_local_dirs'] = tgm.complement(ok, countries_dirs)
    previous_task_local_dirs = task_state[task_state[task]['required_task']]['local_dirs']
    task_state[task]['to_process_wihout_required_local_dirs'] = tgm.complement(tgm.complement(previous_task_ok, ok), previous_task_local_dirs)

# convert to length
task_state_resume = copy.deepcopy(task_state)
for task,val in task_state.items():
    for k,v in task_state_resume[task].items():
        if k in ['dir', 'required_task']: continue
        task_state_resume[task][k] = len(v)

214

In [47]:
pd.DataFrame(task_state_resume).T

,dir,required_task,ok,pending,to_process,local_dirs,ok_wihout_local_dirs,to_process_wihout_required_local_dirs
scrape,data/raw/osm countries queries,scrape,83,131,0,83,0,0
clean,data/cleaned,scrape,83,131,0,83,0,0
test_basic,data/tests results/osm basic test,clean,0,214,83,72,0,0

# Fix process state

## * initial state

In [90]:
osmMetaCountrDict = tgm.load(DATA_DIR / 'osmMetaCountrDict.json')
print(len(osmMetaCountrDict))

241

In [91]:
process_state = {}
for country in osmMetaCountrDict.keys():
    process_state[country] = {
        "scrape": {
            "status": "pending",
            "type": 'normal',
            "last_run": None,
            "error": None
        },
        "clean": {
            "status": "pending",
            "last_run": None,
            "error": None
        },
        "test_basic": {
            "status": "pending",
            "last_run": None,
            "error": None
        },
        "test_first_level": {
            "status": "pending",
            "last_run": None,
            "error": None
        },
        "test_duplicates": {
            "status": "pending",
            "last_run": None,
            "error": None
        },
        "fix": {
            "status": "pending",
            "last_run": None,
            "error": None
        }
    }
print(len(process_state))

241

In [154]:
tgm.dump(DATA_DIR / 'process_state.json', process_state)

## * update state

### * scrape

In [166]:
countries_dirs = [dir for dir in (DATA_DIR / 'raw/osm countries queries').glob('*') if dir.is_dir()]
print(len(countries_dirs))

97

In [33]:
chunks_countries = []
for country_dir in countries_dirs:
    if country_dir.is_dir():
        files = [f for f in country_dir.glob('*')]
        if len(files) > 1:
            chunks_countries.append(country_dir.name)
chunks_countries

['Argentina', 'Peru', 'UnitedStates']

In [95]:
import datetime
for country in processed_countries:
    process_state[country]['scrape']['status'] = 'ok'
    process_state[country]['scrape']['last_run'] = datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
    if country in chunks_countries:
        state = tgm.load(DATA_DIR / 'raw/osm countries queries' / country / 'state.pkl')
        process_state[country]['scrape']['type'] = 'chunk'
        process_state[country]['scrape']['chunk_state'] = state

In [97]:
process_state['Argentina']

{'scrape': {'status': 'ok',
  'type': 'chunk',
  'last_run': '2025-12-02T16:06:44',
  'error': None,
  'chunk_state': {'2': {'processed': {'286393'},
    'failed': set(),
    'discovered': {'286393'},
    'next_chunk_index': 1},
   '4': {'processed': {'153536',
     '153538',
     '153539',
     '153540',
     '153541',
     '153543',
     '153544',
     '153545',
     '153547',
     '153548',
     '153549',
     '153550',
     '153551',
     '153552',
     '153553',
     '153554',
     '153556',
     '153558',
     '1606727',
     '1632167',
     '2405230',
     '2849847',
     '301542',
     '3082668',
     '3592494'},
    'failed': set(),
    'discovered': {'153536',
     '153538',
     '153539',
     '153540',
     '153541',
     '153543',
     '153544',
     '153545',
     '153547',
     '153548',
     '153549',
     '153550',
     '153551',
     '153552',
     '153553',
     '153554',
     '153556',
     '153558',
     '1606727',
     '1632167',
     '2405230',
     '2849847',
     '301542',
     '3082668',
     '3592494'},
    'next_chunk_index': 2},
   '6': {'processed': {'11174871',
     '12126376',
     '12126377',
     '12126378',
     '12126379',
     '12126420',
     '15087661',
     '15087662',
     '15087663',
     '15087664',
     '15087665',
     '15087666',
     '15087667',
     '15087668',
     '15087669',
     '15087670',
     '15087671',
     '15087672',
     '15087673',
     '15092636',
     '15092637',
     '15092638',
     '15092639',
     '15092640',
     '15092641',
     '15092642',
     '15092643',
     '15092644',
     '15092645',
     '15092646',
     '15092647',
     '15092648',
     '15092649',
     '15092689',
     '15092690',
     '17262432',
     '17845983',
     '17845984',
     '17845985',
     '17846261',
     '17846262',
     '17846528',
     '17846529',
     '17846530',
     '17846531',
     '17846532',
     '17846942',
     '17846943',
     '17846944',
     '17846945',
     '17848791',
     '17848792',
     '17848793',
     '17848794',
     '17848795',
     '17848796',
     '17848797',
     '17850017',
     '17850018',
     '17850019',
     '17869452',
     '17869453',
     '17869454',
     '17869455',
     '17869456',
     '17869457',
     '17869458',
     '17869459',
     '17869460',
     '17869461',
     '17869462',
     '17869463',
     '17871783',
     '17871784',
     '17871785',
     '17871786',
     '17871787',
     '17871790',
     '17875115',
     '17875116',
     '17875117',
     '17875118',
     '17875119',
     '17875120',
     '17875121',
     '17875122',
     '17875123',
     '17875357',
     '17875358',
     '17875359',
     '17875360',
     '17875361',
     '17877789',
     '17877790',
     '17877791',
     '17877792',
     '17877793',
     '17877794',
     '17877795',
     '17878749',
     '17878750',
     '17878751',
     '17878752',
     '17878753',
     '17881230',
     '17881231',
     '17881232',
     '17881233',
     '17881234',
     '17881235',
     '17881236',
     '17881237',
     '17881238',
     '17882895',
     '17882896',
     '17882897',
     '17882898',
     '17882899',
     '17887906',
     '17887907',
     '17887908',
     '17887909',
     '17887910',
     '17887911',
     '17887912',
     '17887913',
     '17887914',
     '17887915',
     '17887916',
     '17887917',
     '17887918',
     '17887919',
     '17887920',
     '17959436',
     '17959437',
     '17959438',
     '17981732',
     '18167416',
     '18308066',
     '18308067',
     '18308068',
     '18308069',
     '18308070',
     '18308071',
     '18308072',
     '19285516',
     '19285517',
     '19285518',
     '19285519',
     '19607078',
     '19672523',
     '19686379',
     '19690600',
     '1974213',
     '1980481',
     '1980558',
     '1980749',
     '2804011',
     '2804280',
     '2804296',
     '2804297',
     '2807035',
     '2807519',
     '2808072',
     '2808893',
     '2808894',
     '2815237',
     '2815660',
     '2816167',
     '2816169',
     '2816171',
     '2816172',
     '2822484',
     '2822549',
     '2822577',
     '2822578',
     '2827467',
     '2827803',
     '2828499',
     '2828581',
     '2828850',
     '2828851',
     '2840162',
     '2840190',
     '2840474',
     '2840682',
     '2840711',
     '2840712',
     '2843435',
     '2843436',
     '2843440',
     '2843441',
     '2854372',
     '2854728',
     '2854729',
     '2856953',
     '2856954',
     '2869367',
     '2869944',
     '2869970',
     '2869983',
     '2870151',
     '2870359',
     '2870360',
     '2884192',
     '2884698',
     '2884712',
     '2884859',
     '2884874',
     '2884875',
     '2889628',
     '2889632',
     '2892660',
     '2893126',
     '2894018',
     '2894606',
     '2894612',
     '2899336',
     '2899430',
     '2899456',
     '2900991',
     '2901022',
     '2901023',
     '2904790',
     '2904799',
     '2904816',
     '2904822',
     '2904823',
     '2904824',
     '2911578',
     '2911675',
     '2911676',
     '2911677',
     '2911703',
     '2911719',
     '2911903',
     '2911904',
     '2911906',
     '2911907',
     '2917872',
     '2917910',
     '2918386',
     '2918394',
     '2918398',
     '2918400',
     '2918402',
     '2918403',
     '2918404',
     '2921539',
     '2921840',
     '2921922',
     '2921926',
     '2921990',
     '2922030',
     '2922031',
     '2922038',
     '2922040',
     '2922041',
     '2922042',
     '2922043',
     '2922044',
     '2922045',
     '2922046',
     '2940097',
     '2940127',
     '2940176',
     '2940614',
     '2940901',
     '2941130',
     '2941573',
     '2941574',
     '2941600',
     '2941629',
     '2941633',
     '2941710',
     '2941711',
     '2946668',
     '2946687',
     '2950791',
     '2950993',
     '2951113',
     '2951114',
     '2951129',
     '2951130',
     '2951138',
     '2951139',
     '2955009',
     '2955010',
     '2955021',
     '2955053',
     '2955054',
     '2955078',
     '2955079',
     '2955080',
     '2955086',
     '2956912',
     '2956913',
     '2956914',
     '2958037',
     '2958038',
     '2958039',
     '2959642',
     '2959643',
     '2960921',
     '2960933',
     '2960944',
     '2961079',
     '2961220',
     '2961227',
     '2961243',
     '2961248',
     '2961249',
     '2961252',
     '2962909',
     '2962912',
     '2962924',
     '2962926',
     '2964447',
     '2964448',
     '2964491',
     '2964503',
     '2964971',
     '2964976',
     '2964979',
     '2964981',
     '2964983',
     '2964995',
     '2964997',
     '2964999',
     '2965011',
     '2965016',
     '2965024',
     '2965025',
     '2966988',
     '2966989',
     '2966990',
     '2966991',
     '2966992',
     '2966994',
     '2966995',
     '2966999',
     '2967000',
     '2969998',
     '2969999',
     '2970000',
     '2970018',
     '2970019',
     '2970020',
     '2970021',
     '2970022',
     '2972145',
     '2972157',
     '2972158',
     '2975770',
     '2975778',
     '2975791',
     '2975806',
     '2975811',
     '2975829',
     '2975830',
     '2975831',
     '2975854',
     '2975856',
     '2978473',
     '2978474',
     '2978476',
     '2978486',
     '2978504',
     '2978505',
     '2980515',
     '2980516',
     '2980561',
     '2980562',
     '2980563',
     '2980564',
     '2980565',
     '2980566',
     '2980567',
     '2980568',
     '2980569',
     '2980570',
     '2980571',
     '2980572',
     '2984938',
     '2986366',
     '2988741',
     '2989586',
     '2989596',
     '2989604',
     '2989639',
     '2989640',
     '2989646',
     '2989709',
     '2989712',
     '2989763',
     '2989800',
     '2989805',
     '2992002',
     '2992003',
     '2992004',
     '2992005',
     '2992006',
     '2993093',
     '2993134',
     '2993135',
     '2993818',
     '2993821',
     '2993823',
     '2993828',
     '2993830',
     '3000569',
     '3000596',
     '3000597',
     '3000598',
     '3005417',
     '3005418',
     '3005419',
     '3005420',
     '3006741',
     '3006742',
     '3006743',
     '3006798',
     '3011702',
     '3011834',
     '3011839',
     '3011854',
     '3011863',
     '3013363',
     '3013379',
     '3013380',
     '3013408',
     '3013409',
     '3013410',
     '3013411',
     '3013412',
     '3018866',
     '3018867',
     '3020343',
     '3020351',
     '3023072',
     '3023107',
     '3023108',
     '3028097',
     '3028098',
     '3028099',
     '3030373',
     '3030374',
     '3030375',
     '3030376',
     '3030377',
     '3030378',
     '3030379',
     '3032177',
     '3048754',
     '3048755',
     '3048756',
     '3049494',
     '3049495',
     '3049496',
     '3049497',
     '6597830',
     '6597871',
     '6597872',
     '6597873',
     '6597874',
     '6597875',
     '6597876',
     '6597892',
     '6597893',
     '6597912',
     '6597913',
     '6601953',
     '6614856',
     '6614857',
     '6614858',
     '6614859',
     '6660902',
     '6660986',
     '6660987',
     '6660988',
     '6660989',
     '6660990',
     '6660991',
     '6660992',
     '6660998',
     '6660999',
     '6661006',
     '6661013',
     '6661014',
     '6661019',
     '6661020',
     '6661021',
     '6661022',
     '6661102',
     '6661103',
     '6661104',
     '6661105',
     '6661106',
     '6661107',
     '6661119',
     '6661120',
     '6661132',
     '6661140',
     '6661141',
     '6664669',
     '6664670',
     '6664671',
     '6664672',
     '6664681',
     '6664682',
     '6664701',
     '6664711',
     '6664712',
     '9404084',
     '9479856',
     '9491496',
     '9495290',
     '9500285',
     '9502101',
     '9502102',
     '9504269',
     '9504270',
     '9504808',
     '9504809',
     '9504810',
     '9507284',
     '9507285',
     '9507286',
     '9507287',
     '9507288',
     '9507355',
     '9507361',
     '9507373',
     '9509569',
     '9509570',
     '9512033',
     '9512034',
     '9512075',
     '9513179',
     '9513180',
     '9513181',
     '9515466',
     '9515705',
     '9515850',
     '9515863',
     '9517701',
     '9517787',
     '9518187',
     '9518205',
     '9518206',
     '9519744',
     '9520639',
     '9523133',
     '9523190',
     '9523211',
     '9526508',
     '9526515',
     '9526660',
     '9527027',
     '9527047',
     '9527243',
     '9527244',
     '9529692',
     '9529693',
     '9529694',
     '9529695',
     '9529696',
     '9530646',
     '9530685',
     '9530840',
     '9530841',
     '9530842',
     '9533660',
     '9533661',
     '9533662',
     '9533663',
     '9533664',
     '9533735',
     '9533736',
     '9533737',
     '9533738',
     '9533739',
     '9535351',
     '9535352',
     '9535353',
     '9535482',
     '9535483',
     '9535491',
     '9539693',
     '9539694',
     '9539695',
     '9539808',
     '9540420',
     '9540421',
     '9540422',
     '9540423',
     '9560294',
     '9560295',
     '9560296',
     '9561095',
     '9561322',
     '9561323',
     '9561406',
     '9561407',
     '9561408',
     '9561435',
     '9561436',
     '9561437',
     '9562518',
     '9562519',
     '9562520',
     '9562521',
     '9563902',
     '9563903',
     '9563904',
     '9563905',
     '9566911',
     '9566912',
     '9566913',
     '9566914',
     '9566915',
     '9569652',
     '9569653',
     '9569654',
     '9569655',
     '9569723',
     '9569724',
     '9569725',
     '9569726',
     '9572671',
     '9572672',
     '9572673',
     '9572674',
     '9572675',
     '9572676',
     '9572677',
     '9572962',
     '9572963',
     '9572964',
     '9572965',
     '9572966',
     '9575744',
     '9575745',
     '9575746',
     '9575747',
     '9575748',
     '9575749',
     '9575750',
     '9575794',
     '9578292',
     '9578293',
     '9578294',
     '9583346',
     '9583406',
     '9583407',
     '9585213',
     '9585214',
     '9585215',
     '9585216',
     '9585217'},
    'failed': set(),
    'discovered': {'11174871',
     '12126376',
     '12126377',
     '12126378',
     '12126379',
     '12126420',
     '15087661',
     '15087662',
     '15087663',
     '15087664',
     '15087665',
     '15087666',
     '15087667',
     '15087668',
     '15087669',
     '15087670',
     '15087671',
     '15087672',
     '15087673',
     '15092636',
     '15092637',
     '15092638',
     '15092639',
     '15092640',
     '15092641',
     '15092642',
     '15092643',
     '15092644',
     '15092645',
     '15092646',
     '15092647',
     '15092648',
     '15092649',
     '15092689',
     '15092690',
     '17262432',
     '17845983',
     '17845984',
     '17845985',
     '17846261',
     '17846262',
     '17846528',
     '17846529',
     '17846530',
     '17846531',
     '17846532',
     '17846942',
     '17846943',
     '17846944',
     '17846945',
     '17848791',
     '17848792',
     '17848793',
     '17848794',
     '17848795',
     '17848796',
     '17848797',
     '17850017',
     '17850018',
     '17850019',
     '17869452',
     '17869453',
     '17869454',
     '17869455',
     '17869456',
     '17869457',
     '17869458',
     '17869459',
     '17869460',
     '17869461',
     '17869462',
     '17869463',
     '17871783',
     '17871784',
     '17871785',
     '17871786',
     '17871787',
     '17871790',
     '17875115',
     '17875116',
     '17875117',
     '17875118',
     '17875119',
     '17875120',
     '17875121',
     '17875122',
     '17875123',
     '17875357',
     '17875358',
     '17875359',
     '17875360',
     '17875361',
     '17877789',
     '17877790',
     '17877791',
     '17877792',
     '17877793',
     '17877794',
     '17877795',
     '17878749',
     '17878750',
     '17878751',
     '17878752',
     '17878753',
     '17881230',
     '17881231',
     '17881232',
     '17881233',
     '17881234',
     '17881235',
     '17881236',
     '17881237',
     '17881238',
     '17882895',
     '17882896',
     '17882897',
     '17882898',
     '17882899',
     '17887906',
     '17887907',
     '17887908',
     '17887909',
     '17887910',
     '17887911',
     '17887912',
     '17887913',
     '17887914',
     '17887915',
     '17887916',
     '17887917',
     '17887918',
     '17887919',
     '17887920',
     '17959436',
     '17959437',
     '17959438',
     '17981732',
     '18167416',
     '18308066',
     '18308067',
     '18308068',
     '18308069',
     '18308070',
     '18308071',
     '18308072',
     '19285516',
     '19285517',
     '19285518',
     '19285519',
     '19607078',
     '19672523',
     '19686379',
     '19690600',
     '1974213',
     '1980481',
     '1980558',
     '1980749',
     '2804011',
     '2804280',
     '2804296',
     '2804297',
     '2807035',
     '2807519',
     '2808072',
     '2808893',
     '2808894',
     '2815237',
     '2815660',
     '2816167',
     '2816169',
     '2816171',
     '2816172',
     '2822484',
     '2822549',
     '2822577',
     '2822578',
     '2827467',
     '2827803',
     '2828499',
     '2828581',
     '2828850',
     '2828851',
     '2840162',
     '2840190',
     '2840474',
     '2840682',
     '2840711',
     '2840712',
     '2843435',
     '2843436',
     '2843440',
     '2843441',
     '2854372',
     '2854728',
     '2854729',
     '2856953',
     '2856954',
     '2869367',
     '2869944',
     '2869970',
     '2869983',
     '2870151',
     '2870359',
     '2870360',
     '2884192',
     '2884698',
     '2884712',
     '2884859',
     '2884874',
     '2884875',
     '2889628',
     '2889632',
     '2892660',
     '2893126',
     '2894018',
     '2894606',
     '2894612',
     '2899336',
     '2899430',
     '2899456',
     '2900991',
     '2901022',
     '2901023',
     '2904790',
     '2904799',
     '2904816',
     '2904822',
     '2904823',
     '2904824',
     '2911578',
     '2911675',
     '2911676',
     '2911677',
     '2911703',
     '2911719',
     '2911903',
     '2911904',
     '2911906',
     '2911907',
     '2917872',
     '2917910',
     '2918386',
     '2918394',
     '2918398',
     '2918400',
     '2918402',
     '2918403',
     '2918404',
     '2921539',
     '2921840',
     '2921922',
     '2921926',
     '2921990',
     '2922030',
     '2922031',
     '2922038',
     '2922040',
     '2922041',
     '2922042',
     '2922043',
     '2922044',
     '2922045',
     '2922046',
     '2940097',
     '2940127',
     '2940176',
     '2940614',
     '2940901',
     '2941130',
     '2941573',
     '2941574',
     '2941600',
     '2941629',
     '2941633',
     '2941710',
     '2941711',
     '2946668',
     '2946687',
     '2950791',
     '2950993',
     '2951113',
     '2951114',
     '2951129',
     '2951130',
     '2951138',
     '2951139',
     '2955009',
     '2955010',
     '2955021',
     '2955053',
     '2955054',
     '2955078',
     '2955079',
     '2955080',
     '2955086',
     '2956912',
     '2956913',
     '2956914',
     '2958037',
     '2958038',
     '2958039',
     '2959642',
     '2959643',
     '2960921',
     '2960933',
     '2960944',
     '2961079',
     '2961220',
     '2961227',
     '2961243',
     '2961248',
     '2961249',
     '2961252',
     '2962909',
     '2962912',
     '2962924',
     '2962926',
     '2964447',
     '2964448',
     '2964491',
     '2964503',
     '2964971',
     '2964976',
     '2964979',
     '2964981',
     '2964983',
     '2964995',
     '2964997',
     '2964999',
     '2965011',
     '2965016',
     '2965024',
     '2965025',
     '2966988',
     '2966989',
     '2966990',
     '2966991',
     '2966992',
     '2966994',
     '2966995',
     '2966999',
     '2967000',
     '2969998',
     '2969999',
     '2970000',
     '2970018',
     '2970019',
     '2970020',
     '2970021',
     '2970022',
     '2972145',
     '2972157',
     '2972158',
     '2975770',
     '2975778',
     '2975791',
     '2975806',
     '2975811',
     '2975829',
     '2975830',
     '2975831',
     '2975854',
     '2975856',
     '2978473',
     '2978474',
     '2978476',
     '2978486',
     '2978504',
     '2978505',
     '2980515',
     '2980516',
     '2980561',
     '2980562',
     '2980563',
     '2980564',
     '2980565',
     '2980566',
     '2980567',
     '2980568',
     '2980569',
     '2980570',
     '2980571',
     '2980572',
     '2984938',
     '2986366',
     '2988741',
     '2989586',
     '2989596',
     '2989604',
     '2989639',
     '2989640',
     '2989646',
     '2989709',
     '2989712',
     '2989763',
     '2989800',
     '2989805',
     '2992002',
     '2992003',
     '2992004',
     '2992005',
     '2992006',
     '2993093',
     '2993134',
     '2993135',
     '2993818',
     '2993821',
     '2993823',
     '2993828',
     '2993830',
     '3000569',
     '3000596',
     '3000597',
     '3000598',
     '3005417',
     '3005418',
     '3005419',
     '3005420',
     '3006741',
     '3006742',
     '3006743',
     '3006798',
     '3011702',
     '3011834',
     '3011839',
     '3011854',
     '3011863',
     '3013363',
     '3013379',
     '3013380',
     '3013408',
     '3013409',
     '3013410',
     '3013411',
     '3013412',
     '3018866',
     '3018867',
     '3020343',
     '3020351',
     '3023072',
     '3023107',
     '3023108',
     '3028097',
     '3028098',
     '3028099',
     '3030373',
     '3030374',
     '3030375',
     '3030376',
     '3030377',
     '3030378',
     '3030379',
     '3032177',
     '3048754',
     '3048755',
     '3048756',
     '3049494',
     '3049495',
     '3049496',
     '3049497',
     '6597830',
     '6597871',
     '6597872',
     '6597873',
     '6597874',
     '6597875',
     '6597876',
     '6597892',
     '6597893',
     '6597912',
     '6597913',
     '6601953',
     '6614856',
     '6614857',
     '6614858',
     '6614859',
     '6660902',
     '6660986',
     '6660987',
     '6660988',
     '6660989',
     '6660990',
     '6660991',
     '6660992',
     '6660998',
     '6660999',
     '6661006',
     '6661013',
     '6661014',
     '6661019',
     '6661020',
     '6661021',
     '6661022',
     '6661102',
     '6661103',
     '6661104',
     '6661105',
     '6661106',
     '6661107',
     '6661119',

In [98]:
tgm.dump(DATA_DIR / 'process_state.json', process_state)

### * clean

In [177]:
process_state = tgm.load(DATA_DIR / 'process_state.json')
print(len(process_state))

241

In [191]:
clean_countries = [dir.name for dir in (DATA_DIR / 'normalized').glob('*') if dir.is_dir()]
print(len(clean_countries))

72

In [194]:
scrape_countries = [c for c,v in process_state.items() if v['scrape']['status'] == 'ok']
print(len(scrape_countries))

98

In [195]:
print(len(tgm.complement(scrape_countries, clean_countries)))
print(len(tgm.complement(clean_countries, scrape_countries)))

26
0

In [197]:
import datetime
for country in clean_countries:
    process_state[country]['clean']['status'] = 'ok'
    process_state[country]['clean']['last_run'] = datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S")

In [198]:
tgm.dump(DATA_DIR / 'process_state.json', process_state)

## * general review

In [156]:
# update from automated repo
shutil.copy2(AUTOMATED_REPO_DIR / 'data' / 'process_state.json', DATA_DIR / 'process_state.json')

WindowsPath('c:/Users/gonta/D/study/full stack/projects/administrative divisions osm scrape/data/process_state.json')

In [200]:
process_state = tgm.load(DATA_DIR / 'process_state.json')
print(len(process_state))

241

In [209]:
temp = [c for c, val in process_state.items() if (val['scrape']['status'] == 'ok') and val['clean']['status'] == 'pending']
print(len(temp))

26

In [201]:
import copy
process_state_resume = copy.deepcopy(process_state)
for country, val in process_state_resume.items():
    if val['scrape']['type'] == 'chunk':
        val['scrape']['chunk_state'] = {k:{k2:(len(v2) if type(v2) == set else v2) for k2,v2 in val.items()} for k,val in val['scrape']['chunk_state'].items()}
    process_state_resume[country] = val

In [202]:
rows = []
for country, sections in process_state_resume.items():
    for section_name, info in sections.items():
        rows.append({
            "country": country,
            "task": section_name,
            **info
        })

df = pd.DataFrame(rows)
df = df.sort_values(by=['country','task'])

In [105]:
tph.to_df(process_state_resume['Armenia']).df_peek()

In [106]:
tph.to_df(process_state_resume['Argentina']).df_peek()

In [11]:
df.df_peek()

## * check tasks state

In [203]:
scrape_ok = df.query("task == 'scrape' and status == 'ok'")["country"]
print(len(scrape_ok))

98

In [161]:
df.query("country in @ok_scrape").df_peek()

In [204]:
clean_pending = df.query("country in @ok_scrape").query("task == 'clean' and status == 'pending'")["country"]
print(len(clean_pending))

26

## * filter only sovereign countries

In [6]:
sovereign_countries = tgm.load(DATA_DIR / 'sovereign countries.json')
print(len(sovereign_countries))
process_state = tgm.load(DATA_DIR / "process_state.json")
print(len(process_state))

214
241

In [9]:
process_state_sovereign = {c:v for c,v in process_state.items() if c in sovereign_countries}
print(len(process_state_sovereign))

214

In [10]:
tgm.dump(DATA_DIR / "process_state.json", process_state_sovereign)